---
title: "Entrega2,Limpieza variables"
author: "alexandra Porras"
date: '2022-10-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


*Responsable:Alexandra*
#Variable Crecimiento PBI per cápita

```{r}
CreciPBI="https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/CreciPIB.xls?raw=true"
library(rio)
PBI=import(CreciPBI)
```
```{r}
PBI=PBI[,c(1:2,64)]
```
```{r}
PBI=PBI[-c(1:3),]
```
```{r}
colnames(PBI)=c("Pais","ISO","PBI_2020")
```

```{r}
class(PBI$PBI_2020)
PBI$PBI_2020= as.numeric(PBI$PBI_2020)
str(PBI)
```

#Variable DESEMPLEO

```{r}
Desem="https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/Desempleo.xls?raw=true"
library(rio)
desempleo=import(Desem)
```

```{r}
desempleo=desempleo[,c(1:2,64)]
```
```{r}
colnames(desempleo)=c("Country","ISO","Desempleo_2021")
```
```{r}
desempleo=desempleo[-c(1:3),]
```

```{r}
str(desempleo)
desempleo$Desempleo_2021=as.numeric(desempleo$Desempleo_2021)
```


#Variable Percepción de la corrupción

```{r}
PercepCorru="https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/IndicePercepCorru.xlsx?raw=true"
library(rio)
Corrupcion=import(PercepCorru)
```

```{r}
Corrupcion=Corrupcion[,c(1:4)]
```
```{r}
colnames(Corrupcion)=c("pais","ISO","Region","PCorrupcion_2021")
```
```{r}
Corrupcion=Corrupcion[-c(1:2),]
```

```{r}
str(Corrupcion)
Corrupcion$PCorrupcion_2021=as.numeric(Corrupcion$PCorrupcion_2021)
class(Corrupcion$PCorrupcion_2021)
```

```{r}
merge1=merge(Corrupcion,desempleo)
str(merge1)
```

```{r}
data1=merge(merge1,PBI)
str(data1)
```

```{r}
data1=data1[,-c(5,7)]
```

#VARIABLE DEPENDIENTE: MIGRACION 2022

```{r}
Migra="https://github.com/davilaluis9/Entrega-1-Estad-stica/raw/main/Migracion2022.csv"
library(rio)
migracion=import(Migra)
```

```{r}
migracion=migracion[,c(1:2,4)]
```
```{r}
colnames(migracion)=c("Pay","ISO","Migracion_2022")
```

```{r}
data2=merge(data1,migracion)
str(data2)
data2=data2[,-c(7)]
```

--------------------------------------------------------------
*Responsable=LUIS Davila*

#Variable: CRIMINALIDAD
```{r}
library(rio)
datacrimen = import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/criminalidad1.xlsx?raw=true")
str(datacrimen)
```
```{r}
colnames(datacrimen)[3] = "Criminalidad"
```

```{r}
data3= merge(data2,datacrimen)
str(data3)
```

#Variable: DESIGUALDAD ECONOMICA
```{r}
desieco = import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/desieco.xlsx?raw=true")
str(desieco)
```
```{r}
desieco = desieco[,c(1,3,9)]
str(desieco)
```

```{r}
data4= merge(data3,desieco)
data4=data4[,-c(8,10)]
str(data4)
```

#Variable: Emisiones CO2
```{r}
dataco2 =import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/emisiones%20co2.xls?raw=true")
dataco2=dataco2[,c(1:2,64)]
dataco2=dataco2[-c(1:3),]
colnames(dataco2)[1] = "country-pais"
colnames(dataco2)[2] = "ISO"
colnames(dataco2)[3] = "EmisionesCO2"
```
```{r}
class(dataco2$EmisionesCO2)
dataco2$EmisionesCO2= as.numeric(dataco2$EmisionesCO2)
class(dataco2$EmisionesCO2)
```


```{r}
data5= merge(data4,dataco2)
data5=data5[,-c(10)]
```

------------------------------------------------
*Responsable: Athina*

#Variable: Legitimidad estatal
```{r}
library(dplyr)
library(magrittr)
legitimidad_estatal = import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/legitimidad%20estatal%202021%20(1).xlsx?raw=true")
names(legitimidad_estatal)
legitimidad = select(legitimidad_estatal, Year, Country, ISO, 'P1: State Legitimacy')
colnames(legitimidad)[1] = "Año"
colnames(legitimidad)[2] = "Pais"
colnames(legitimidad)[4] = "LegitimidadEstatal"
```

```{r}
data6= merge(data5,legitimidad)
data6=data6[,-c(11,12)]
```


#Variable: INDICE DE DETERIORO DE PAZ  

```{r}
pazmundial = import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/paz%20mundial.xlsx?raw=true")
names(pazmundial)
paz = select(pazmundial, '2021', iso3c, Country)
colnames(paz)[1] = "Paz"
colnames(paz)[2] = "ISO"
```

```{r}
data7= merge(data6,paz)
data7=data7[,-c(13)]
```


#Variable: Catástrofes (score del Reporte de Amenazas Ecológicas)
```{r}
catastrofe = import("https://github.com/davilaluis9/Entrega-1-Estad-stica/blob/main/catastrofe.xlsx?raw=true")
names(catastrofe)
catastrofe = select(catastrofe, ISO, Country, 'Catastrophic Score')
colnames(catastrofe)[3] = "Catastrofe"
```

```{r}
dataFINAL= merge(data7,catastrofe)
dataFINAL=dataFINAL[,-c(3,13)]
```

```{r}
str(dataFINAL)
```

```{r}
names(dataFINAL)
```

```{r}
dataFINAL = select(dataFINAL, ISO, pais, Migracion_2022, Criminalidad, PCorrupcion_2021, Desempleo_2021, PBI_2020, 'E2: Economic Inequality', EmisionesCO2, Paz, Catastrofe)

```


```{r}
dataFINAL = dataFINAL[-c(28,111),]
dataFINAL = dataFINAL[complete.cases(dataFINAL[,-1,-2]),]
```


```{r}
library(rio)
export(dataFINAL,"DataFINAL6.csv")
```


